import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const CODEGENIE_EXPERIMENTAL = truthy("CODEGENIE_EXPERIMENTAL")
const CODEGENIE_DISABLE_CLAUDE_CODE = truthy("CODEGENIE_DISABLE_CLAUDE_CODE")
const CODEGENIE_DISABLE_CLAUDE_CODE_SKILLS =
  CODEGENIE_DISABLE_CLAUDE_CODE || truthy("CODEGENIE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["CODEGENIE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  CODEGENIE_AUTO_SHARE: truthy("CODEGENIE_AUTO_SHARE"),
  CODEGENIE_AUTO_HEAP_SNAPSHOT: truthy("CODEGENIE_AUTO_HEAP_SNAPSHOT"),
  CODEGENIE_GIT_BASH_PATH: process.env["CODEGENIE_GIT_BASH_PATH"],
  CODEGENIE_CONFIG: process.env["CODEGENIE_CONFIG"],
  CODEGENIE_CONFIG_CONTENT: process.env["CODEGENIE_CONFIG_CONTENT"],
  CODEGENIE_DISABLE_AUTOUPDATE: truthy("CODEGENIE_DISABLE_AUTOUPDATE"),
  CODEGENIE_ALWAYS_NOTIFY_UPDATE: truthy("CODEGENIE_ALWAYS_NOTIFY_UPDATE"),
  CODEGENIE_DISABLE_PRUNE: truthy("CODEGENIE_DISABLE_PRUNE"),
  CODEGENIE_DISABLE_TERMINAL_TITLE: truthy("CODEGENIE_DISABLE_TERMINAL_TITLE"),
  CODEGENIE_SHOW_TTFD: truthy("CODEGENIE_SHOW_TTFD"),
  CODEGENIE_PERMISSION: process.env["CODEGENIE_PERMISSION"],
  CODEGENIE_DISABLE_DEFAULT_PLUGINS: truthy("CODEGENIE_DISABLE_DEFAULT_PLUGINS"),
  CODEGENIE_DISABLE_LSP_DOWNLOAD: truthy("CODEGENIE_DISABLE_LSP_DOWNLOAD"),
  CODEGENIE_ENABLE_EXPERIMENTAL_MODELS: truthy("CODEGENIE_ENABLE_EXPERIMENTAL_MODELS"),
  CODEGENIE_DISABLE_AUTOCOMPACT: truthy("CODEGENIE_DISABLE_AUTOCOMPACT"),
  CODEGENIE_DISABLE_MODELS_FETCH: truthy("CODEGENIE_DISABLE_MODELS_FETCH"),
  CODEGENIE_DISABLE_MOUSE: truthy("CODEGENIE_DISABLE_MOUSE"),
  CODEGENIE_DISABLE_CLAUDE_CODE,
  CODEGENIE_DISABLE_CLAUDE_CODE_PROMPT: CODEGENIE_DISABLE_CLAUDE_CODE || truthy("CODEGENIE_DISABLE_CLAUDE_CODE_PROMPT"),
  CODEGENIE_DISABLE_CLAUDE_CODE_SKILLS,
  CODEGENIE_DISABLE_EXTERNAL_SKILLS: truthy("CODEGENIE_DISABLE_EXTERNAL_SKILLS"),
  CODEGENIE_FAKE_VCS: process.env["CODEGENIE_FAKE_VCS"],
  CODEGENIE_SERVER_PASSWORD: process.env["CODEGENIE_SERVER_PASSWORD"],
  CODEGENIE_SERVER_USERNAME: process.env["CODEGENIE_SERVER_USERNAME"],
  CODEGENIE_ENABLE_QUESTION_TOOL: truthy("CODEGENIE_ENABLE_QUESTION_TOOL"),

  // Experimental
  CODEGENIE_EXPERIMENTAL,
  CODEGENIE_EXPERIMENTAL_FILEWATCHER: Config.boolean("CODEGENIE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CODEGENIE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("CODEGENIE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CODEGENIE_EXPERIMENTAL_ICON_DISCOVERY: CODEGENIE_EXPERIMENTAL || truthy("CODEGENIE_EXPERIMENTAL_ICON_DISCOVERY"),
  CODEGENIE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("CODEGENIE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  CODEGENIE_ENABLE_EXA: truthy("CODEGENIE_ENABLE_EXA") || CODEGENIE_EXPERIMENTAL || truthy("CODEGENIE_EXPERIMENTAL_EXA"),
  CODEGENIE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("CODEGENIE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  CODEGENIE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("CODEGENIE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  CODEGENIE_EXPERIMENTAL_OXFMT: CODEGENIE_EXPERIMENTAL || truthy("CODEGENIE_EXPERIMENTAL_OXFMT"),
  CODEGENIE_EXPERIMENTAL_LSP_TY: truthy("CODEGENIE_EXPERIMENTAL_LSP_TY"),
  CODEGENIE_EXPERIMENTAL_LSP_TOOL: CODEGENIE_EXPERIMENTAL || truthy("CODEGENIE_EXPERIMENTAL_LSP_TOOL"),
  CODEGENIE_EXPERIMENTAL_PLAN_MODE: CODEGENIE_EXPERIMENTAL || truthy("CODEGENIE_EXPERIMENTAL_PLAN_MODE"),
  CODEGENIE_EXPERIMENTAL_SCOUT: CODEGENIE_EXPERIMENTAL || truthy("CODEGENIE_EXPERIMENTAL_SCOUT"),
  CODEGENIE_EXPERIMENTAL_MARKDOWN: !falsy("CODEGENIE_EXPERIMENTAL_MARKDOWN"),
  CODEGENIE_ENABLE_PARALLEL: truthy("CODEGENIE_ENABLE_PARALLEL") || truthy("CODEGENIE_EXPERIMENTAL_PARALLEL"),
  CODEGENIE_MODELS_URL: process.env["CODEGENIE_MODELS_URL"],
  CODEGENIE_MODELS_PATH: process.env["CODEGENIE_MODELS_PATH"],
  CODEGENIE_DISABLE_EMBEDDED_WEB_UI: truthy("CODEGENIE_DISABLE_EMBEDDED_WEB_UI"),
  CODEGENIE_DB: process.env["CODEGENIE_DB"],
  CODEGENIE_DISABLE_CHANNEL_DB: truthy("CODEGENIE_DISABLE_CHANNEL_DB"),
  CODEGENIE_SKIP_MIGRATIONS: truthy("CODEGENIE_SKIP_MIGRATIONS"),
  CODEGENIE_STRICT_CONFIG_DEPS: truthy("CODEGENIE_STRICT_CONFIG_DEPS"),

  CODEGENIE_WORKSPACE_ID: process.env["CODEGENIE_WORKSPACE_ID"],
  CODEGENIE_EXPERIMENTAL_WORKSPACES: CODEGENIE_EXPERIMENTAL || truthy("CODEGENIE_EXPERIMENTAL_WORKSPACES"),
  CODEGENIE_EXPERIMENTAL_EVENT_SYSTEM: CODEGENIE_EXPERIMENTAL || truthy("CODEGENIE_EXPERIMENTAL_EVENT_SYSTEM"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get CODEGENIE_DISABLE_PROJECT_CONFIG() {
    return truthy("CODEGENIE_DISABLE_PROJECT_CONFIG")
  },
  get CODEGENIE_TUI_CONFIG() {
    return process.env["CODEGENIE_TUI_CONFIG"]
  },
  get CODEGENIE_CONFIG_DIR() {
    return process.env["CODEGENIE_CONFIG_DIR"]
  },
  get CODEGENIE_PURE() {
    return truthy("CODEGENIE_PURE")
  },
  get CODEGENIE_PLUGIN_META_FILE() {
    return process.env["CODEGENIE_PLUGIN_META_FILE"]
  },
  get CODEGENIE_CLIENT() {
    return process.env["CODEGENIE_CLIENT"] ?? "cli"
  },
}
